name: get_permission
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/yuraware/get_permission

flutter:
  plugin:
    platforms:
      android:
        package: com.yuraware.get_permission
        pluginClass: GetPermissionPlugin
      ios:
        pluginClass: GetPermissionPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
